import type { Bias } from './types';

export const BIASES: Bias[] = [
  { id: 0, name: 'Anchoring', description: 'First price sets reference', example: 'A $100 shirt marked down to $50 seems like a great deal.' },
  { id: 1, name: 'Social Proof', description: 'Others are doing it', example: '"Bestseller" tags on products or showing customer testimonials.' },
  { id: 2, name: 'Scarcity', description: 'Limited availability', example: '"Only 3 left in stock!" or "Limited time offer!" messages.' },
  { id: 3, name: 'Loss Aversion', description: 'Fear of missing out', example: 'Free trials that convert to paid subscriptions if not cancelled.' },
  { id: 4, name: 'Reciprocity', description: 'Give to receive', example: 'A free sample in a store makes you feel obligated to buy.' },
  { id: 5, name: 'Authority', description: 'Expert endorsement', example: '"9 out of 10 dentists recommend" a certain toothpaste.' },
  { id: 6, name: 'Framing', description: 'How information is presented', example: '"80% fat-free" vs. "20% fat" on a food label.' },
  { id: 7, name: 'Default Effect', description: 'Pre-selected option', example: 'A software installation with pre-checked boxes for extra toolbars.' },
  { id: 8, name: 'Bandwagon', description: 'Everyone’s doing it', example: 'Showing how many people have already purchased a product.' },
  { id: 9, name: 'Decoy Effect', description: 'Third option influences choice', example: 'Small popcorn $3, Medium $6.50, Large $7. The medium is a decoy.' },
  { id: 10, name: 'Endowment', description: 'Value what you try', example: 'Test driving a car makes you value it more and more likely to buy.' },
  { id: 11, name: 'Commitment', description: 'Small yes to big yes', example: 'Asking for an email signup before asking for a purchase.' },
  { id: 12, name: 'Urgency', description: 'Time pressure', example: 'Countdown timers for a sale ending soon.' },
  { id: 13, name: 'Choice Paradox', description: 'Fewer options feel better', example: 'A curated menu is less overwhelming than one with 100 items.' },
  { id: 14, name: 'Priming', description: 'Subtle cues influence behavior', example: 'Playing French music in a wine shop may increase French wine sales.' },
  { id: 15, name: 'Confirmation Bias', description: 'Reinforces beliefs', example: 'A brand that aligns with your values makes you favor its products.' },
  { id: 16, name: 'Nostalgia', description: 'Connection to the past', example: 'Coke using vintage-style bottles and ads to evoke happy memories.' },
  { id: 17, name: 'Zero Price', description: 'The power of “free”', example: '"Buy one, get one free" deals that entice you to spend more.' },
  { id: 18, name: 'Sunk Cost', description: 'Continue because already invested', example: 'Finishing a terrible movie because you paid for the ticket.' },
  { id: 19, name: 'Peak-End Rule', description: 'Last moment remembered', example: 'A hotel leaving a chocolate on your pillow on the last night.' },
  { id: 20, name: 'Halo Effect', description: 'One positive = all good', example: 'Assuming a well-designed product is also high-quality and reliable.' },
  { id: 21, name: 'Status Quo', description: 'Preference for no change', example: 'Sticking with your current mobile provider to avoid the hassle of switching.' },
  { id: 22, name: 'Foot-in-the-Door', description: 'Start small, build commitment', example: 'Asking to sign a petition, then later asking for a donation.' },
  { id: 23, name: 'Rhyme-as-Reason', description: 'Rhymes feel true', example: 'Catchy, rhyming slogans that are more memorable and persuasive.' },
  { id: 24, name: 'Mere Exposure', description: 'Familiarity breeds liking', example: 'Seeing the same ad multiple times makes you more likely to trust the brand.' }
];

export const GAME_DURATION_SECONDS = 60 * 60; // 60 minutes

export const STARTUPS: string[] = [
  "Caia Cosmetics",
  "Who Gives A Crap",
  "Drowsy",
  "merit",
  "Teapigs",
  "Yfoods",
  "Healf",
  "Mariella photography",
  "Dash Water",
  "Auxia",
  "Kaybeauty",
  "Jetlost",
  "Surreal",
  "Whoop",
  "Gunia Project",
  "Graza",
  "Spark Drinks",
  "Huel",
  "Zero Labs",
  "Zilch",
  "Skydio",
  "DCYPHERBeauty",
  "Snoop.app",
  "Bazhane",
  "Glossier",
  "Tenzing",
  "eight sleep",
  "Pharmacity",
  "ryft",
  "Workflow",
  "UVU",
  "Edeniste",
  "SURREAL",
  "Liju",
  "Wild",
  "Oura"
];